### ISSUE TITLE
SKU setting in az aks create

### ISSUE THREAD

**Issue by mikmaksoft** [jamesbannan/pluralsight#10]
When running the course the node-vm-size setting of Standard_DS1_v2 seems to cause an error until changed to Standard_DS2_v2

**Comment by jamesbannan** [comment]
What's the error?

**Comment by w7089** [comment]
@jamesbannan the error is 

`Operation failed with status: 'Bad Request'. Details: System node pool must use VM sku with more than 2 cores and 4GB memory. Nodepool name: nodepool1.` 

@mikmaksoft i tried to change `--node-vm-size Standard_DS1_v2` to `--node-vm-size Standard_DS2_v2`, but then get below error. Did you use location `australiaeast` as in the course?

`Operation failed with status: 'Bad Request'. Details: The VM size of AgentPoolProfile:nodepool1 is not allowed in your subscription in location 'australiaeast'. The available VM sizes are 'standard_d16a_v4,standard_d16as_v4,standard_d2a_v4,standard_d2as_v4,standard_d32a_v4,standard_d32as_v4,standard_d48a_v4,standard_d48as_v4,standard_d4a_v4,standard_d4as_v4,standard_d64a_v4,standard_d64as_v4,standard_d8a_v4,standard_d8as_v4,standard_d96a_v4,standard_d96as_v4,standard_e16-4as_v4,standard_e16-8as_v4,standard_e16a_v4,standard_e16as_v4,standard_e20a_v4,standard_e20as_v4,standard_e2a_v4,standard_e2as_v4,standard_e32-16as_v4,standard_e32-8as_v4,standard_e32a_v4,standard_e32as_v4,standard_e4-2as_v4,standard_e48a_v4,standard_e48as_v4,standard_e4a_v4,standard_e4as_v4,standard_e64-16as_v4,standard_e64-32as_v4,standard_e64a_v4,standard_e64as_v4,standard_e8-2as_v4,standard_e8-4as_v4,standard_e80is_v4,standard_e8a_v4,standard_e8as_v4,standard_e96-24as_v4,standard_e96-48as_v4,standard_e96a_v4,standard_e96as_v4,standard_g1,standard_g2,standard_g3,standard_g4,standard_g5,standard_gs1,standard_gs2,standard_gs3,standard_gs4,standard_gs4-4,standard_gs4-8,standard_gs5,standard_gs5-16,standard_gs5-8,standard_h16,standard_h16m,standard_h16mr,standard_h16r,standard_h8,standard_h8m,standard_l16s,standard_l16s_v2,standard_l32s,standard_l32s_v2,standard_l48s_v2,standard_l4s,standard_l64s_v2,standard_l80s_v2,standard_l8s,standard_l8s_v2,standard_m128,standard_m128-32ms,standard_m128-64ms,standard_m128m,standard_m128ms,standard_m128s,standard_m16-4ms,standard_m16-8ms,standard_m16ms,standard_m208ms_v2,standard_m208s_v2,standard_m32-16ms,standard_m32-8ms,standard_m32ls,standard_m32ms,standard_m32ts,standard_m416-208ms_v2,standard_m416-208s_v2,standard_m416ms_v2,standard_m416s_v2,standard_m64,standard_m64-16ms,standard_m64-32ms,standard_m64ls,standard_m64m,standard_m64ms,standard_m64s,standard_m8-2ms,standard_m8-4ms,standard_m8ms,standard_nc12,standard_nc12_promo,standard_nc12s_v3,standard_nc16as_t4_v3,standard_nc24,standard_nc24_promo,standard_nc24r,standard_nc24r_promo,standard_nc24rs_v3,standard_nc24s_v3,standard_nc4as_t4_v3,standard_nc6,standard_nc64as_t4_v3,standard_nc6_promo,standard_nc6s_v3,standard_nc8as_t4_v3,standard_nv12s_v3,standard_nv24s_v3,standard_nv48s_v3' For more details, please visit https://aka.ms/cpu-quota`
