### ISSUE TITLE
Script throwing error because some of the Azure commands are deprecated 

### ISSUE THREAD

**Issue by kiransqldba** [jamesbannan/pluralsight#2]
Hello James,

I am currently leaning your course through pluralsight and first issue I got when I executed Create-CourseEnvironmentARM script because many of the Azure commands are deprecated

I replaced with few of the new commands and also removed switch-AzureMode Command (deprecated), after executed script and getting below output

cmdlet Test-AzureRmResourceGroupDeployment at command pipeline position 1
Supply values for the following parameters:
(Type !? for Help.)
TemplateFile: 

I tried different parameters in Templatefile but it's throwing error,

Can you please help me here?

Thanks in Advance.

-Kiran

**Comment by jamesbannan** [comment]
Hi @kiransqldba - wow I must apologise, but this issue completely flew right past me. Although I'm guessing that you've moved on from this course, was this problem ever resolved?

**Comment by nalrao** [comment]
Hello James,

Hope you are doing good.

I am currently going through "Deploying an AKS cluster" in azure but while executing below command i am getting following error. Kindly help me to resolve the issue.

deployment=$(az group deployment create --resource-group $(echo $group | jq .name -r) --name ${name} --template-file ${templateFile} --verbose)
Error: **az group deployment create: error: argument --resource-group/-g: expected one argument**

Thanks in advance for your help.

**Comment by jamesbannan** [comment]
Closing this and moved latest comment to new issue
