### ISSUE TITLE
Terraform init fails at azure-loganalytics.tf

### ISSUE THREAD

**Issue by sivasubramanian95** [jamesbannan/pluralsight#3]
Hi James,
         Happy to follow this course and the hands-on.Unfortunately,I stuck on initializing terraform for AKS cluster creation at deployAKSsolution.sh..
`terraform init` 
*****************
Error: Error parsing /home/User/AKS/pluralsight/azure-devops-kubernetes-infrastructure/module-terraform/terraform/azure-loganalytics.tf: At 12:13: unexpected token while parsing list: IDENT
*****************
Assistance Please!!!

**Comment by jamesbannan** [comment]
Hi @sivasubramanian95 - which version of Terraform are you using? Can you please do a `terraform version` and paste the output?

**Comment by jamesbannan** [comment]
@sivasubramanian95 hope that you managed to get this issue resolved. I will close the issue.
