### ISSUE TITLE
Issue with accountName in createTFRemoteState.sh

### ISSUE THREAD

**Issue by madhubysani01** [jamesbannan/pluralsight#9]
Hi James,
createTFRemoteState.sh  hangs while creating  the  accountName.

cat /dev/urandom | tr -dc 'a-z0-9' | fold -w 12 | head -n 1)

Used random name to proceed further.

Thanks
Madhu

**Comment by jamesbannan** [comment]
Thanks - what operating system did you run the script on?

**Comment by jamesbannan** [comment]
Closing this issue
